version: '3'
services:
    discovery:
        image: scalable/discovery-service
        build: /DiscoveryService
        ports:
            - "8761:8761"
    customer-service:
        image: scalable/customer-service
        build: /CustomerService
        environment:
          EUREKA_SERVER: "http://discovery:8761/eureka"
        ports:
            - "8000:8000"
        depends_on:
            - discovery
    car-maintenance-service:
        image: scalable/car-maintenance-service
        build: /CarMaintenanceService
        environment:
          EUREKA_SERVER: "http://discovery:8761/eureka"
        ports:
            - "8001:8001"
        depends_on:
            - discovery     