version: '3'
services:
    discovery:
        image: scalable/discovery-service
        build: /DiscoveryService
        ports:
            - "8761:8761"
    user-service:
        image: scalable/user-service
        build: /UserService
        environment:
          EUREKA_SERVER: "http://discovery:8761/eureka"
        ports:
            - "8080:8080"
        depends_on:
            - discovery
    car-service:
        image: scalable/car-service
        build: /CarService
        environment:
          EUREKA_SERVER: "http://discovery:8761/eureka"
        ports:
            - "8080:8082"
        depends_on:
            - discovery     