apiVersion: v1
kind: Service
metadata:
  name: CarMaintenanceService
spec:
  selector:
    app: CarMaintenanceService
  ports:
    - port: 35360
      targetPort: 2310
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CarMaintenanceService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CarMaintenanceService
  template:
    metadata:
      labels:
        app: CarMaintenanceService
    spec:
      containers:
        - name: CarMaintenanceService
          image: scalable/CarMaintenanceService:v1
          ports:
            - containerPort: 2310
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "0.5"
              memory: "64Mi"
