apiVersion: v1
kind: Service
metadata:
  name: CustomerService
spec:
  selector:
    app: CustomerService
  ports:
    - port: 35350
      targetPort: 2300
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerService
  template:
    metadata:
      labels:
        app: CustomerService
    spec:
      containers:
        - name: CustomerService
          image: scalable/CustomerService:v1
          ports:
            - containerPort: 2300
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "0.5"
              memory: "64Mi"
